"""
Path constants for Shrink package.
"""

DATA_PATH = f"./data"


RESIDUALS_FOLDER = DATA_PATH + "/compressed/residuals"
BASE_FOLDER = DATA_PATH + "/compressed/base"
QUANTRC_FOLDER = DATA_PATH + "/quantrc"

TURBO_RANGE_CODER_CODES_RESIDUALS_PATH = RESIDUALS_FOLDER + "/codes.rc"
TURBO_RANGE_CODER_CODES_BASE_PATH = BASE_FOLDER + "/codes.rc"

OUTPUT_PATH_BASE = BASE_FOLDER + "/base.csv"

OUTPUT_PATH_RESIDUALS = RESIDUALS_FOLDER + "/residuals.csv"
OUTPUT_PATH_QUANTIRESIDUALS = RESIDUALS_FOLDER + "/quantiresiduals.csv"
OUTPUT_PATH_DEQUANTIRESIDUALS = RESIDUALS_FOLDER + "/dequantiresiduals.csv"
OUTPUT_PATH_NEWORIGINAL = RESIDUALS_FOLDER + "/neworiginal.csv"

QUANTRC_NORMALIZATION = "/quantrc_normalization.npy"
TURBO_CODE_LOCATION = ".\\Turbo-Range-Coder\\turborc.exe"
TURBO_CODE_PARAMETER = "20"
TURBO_RANGE_CODER_CODES_OUT_PATH = QUANTRC_FOLDER + "/codes.rc"
TURBO_RANGE_CODER_NEWORIGINAL_OUT_PATH = QUANTRC_FOLDER + "/neworginal.csv"
